version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  build:
    commands:
      - echo Build started on `date`
      - echo Packaging the application...
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - index.html
    - appspec.yml
    - scripts/**/*